"""
Train LLM-B_phi with belief-SFT data.

Input format is JSONL with a `messages` list, generated by
generate_belief_sft_data.py.  The assistant target is strict JSON.
"""

from __future__ import annotations

# Unsloth must be imported before transformers/trl.
from unsloth import FastLanguageModel

import argparse
import os

import torch
from datasets import load_dataset
from trl import SFTConfig, SFTTrainer


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", default="models/Qwen-Mahjong-V3-Merged")
    parser.add_argument("--data-file", default="belief_sft_data_train.jsonl")
    parser.add_argument("--output-dir", default="qwen-bphi-sft")
    parser.add_argument("--max-seq-length", type=int, default=2048)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--gradient-accumulation", type=int, default=4)
    parser.add_argument("--epochs", type=float, default=2.0)
    parser.add_argument("--learning-rate", type=float, default=8e-5)
    parser.add_argument("--save-steps", type=int, default=100)
    parser.add_argument("--logging-steps", type=int, default=10)
    parser.add_argument("--max-steps", type=int, default=-1)
    parser.add_argument("--report-to", default="none")
    parser.add_argument("--load-in-4bit", action="store_true", default=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    base_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = args.model_path
    if not os.path.isabs(model_path):
        model_path = os.path.join(base_dir, model_path)

    print(f"[B_phi SFT] model={model_path}")
    print(f"[B_phi SFT] data={args.data_file}")
    print(f"[B_phi SFT] output={args.output_dir}")

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_path,
        max_seq_length=args.max_seq_length,
        dtype=None,
        load_in_4bit=args.load_in_4bit,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    dataset = load_dataset("json", data_files=args.data_file, split="train")

    def formatting_prompts_func(examples):
        texts = []
        for messages in examples["messages"]:
            text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
            texts.append(text)
        return {"text": texts}

    dataset = dataset.map(formatting_prompts_func, batched=True)

    training_args = SFTConfig(
        output_dir=args.output_dir,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation,
        warmup_steps=20,
        num_train_epochs=args.epochs,
        max_steps=args.max_steps,
        learning_rate=args.learning_rate,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_strategy="steps",
        optim="adamw_8bit",
        weight_decay=0.01,
        seed=3407,
        report_to=args.report_to,
        dataset_text_field="text",
        max_length=args.max_seq_length,
        dataset_num_proc=4,
        packing=True,
    )

    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset,
        args=training_args,
    )

    trainer.train()
    model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    print(f"[B_phi SFT] saved adapter/tokenizer to {args.output_dir}")


if __name__ == "__main__":
    main()
