"""
Train MASK-SFT on heuristic L2 teacher data.

Input format is the JSONL generated by generate_mask_sft_data.py:
  {"messages": [{"role": "system", ...}, {"role": "user", ...}, {"role": "assistant", ...}], ...}

The output is a LoRA adapter by default.  Merge it into a full model only after
the adapter passes the Gate1/V4-style evaluation.
"""

from __future__ import annotations

# Unsloth must be imported before transformers/trl.
from unsloth import FastLanguageModel

import argparse
import json
import os
from pathlib import Path

import torch
from datasets import load_dataset
from trl import SFTConfig, SFTTrainer


DEFAULT_DATA_FILE = "MASK_SFT_teacher_l2_mc_3seeds_200games/mask_sft_l2_mc_3seeds_200games.jsonl"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", default="models/Qwen-Mahjong-V4-GRPO-Merged")
    parser.add_argument("--data-file", default=DEFAULT_DATA_FILE)
    parser.add_argument("--output-dir", default="qwen-mask-sft-l2-mc-v5")
    parser.add_argument("--max-seq-length", type=int, default=4096)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--gradient-accumulation", type=int, default=8)
    parser.add_argument("--epochs", type=float, default=2.0)
    parser.add_argument("--learning-rate", type=float, default=5e-5)
    parser.add_argument("--warmup-steps", type=int, default=50)
    parser.add_argument("--save-steps", type=int, default=100)
    parser.add_argument("--logging-steps", type=int, default=10)
    parser.add_argument("--max-steps", type=int, default=-1)
    parser.add_argument("--report-to", default="none")
    parser.add_argument("--load-in-4bit", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=16)
    parser.add_argument("--dataset-num-proc", type=int, default=4)
    parser.add_argument("--packing", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--seed", type=int, default=3407)
    parser.add_argument("--print-data-stats", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def resolve_path(base_dir: str, value: str) -> str:
    return value if os.path.isabs(value) else os.path.join(base_dir, value)


def print_data_stats(data_file: str) -> None:
    path = Path(data_file)
    counts = {}
    rows = 0
    if not path.exists():
        print(f"[MASK-SFT] data stats skipped, file not found: {data_file}")
        return
    with path.open(encoding="utf-8") as f:
        for line in f:
            rows += 1
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            mode = row.get("meta", {}).get("mode", "unknown")
            counts[mode] = counts.get(mode, 0) + 1
    print(f"[MASK-SFT] rows={rows} mode_counts={counts}")


def main() -> None:
    args = parse_args()
    base_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = resolve_path(base_dir, args.model_path)
    data_file = resolve_path(base_dir, args.data_file)
    output_dir = resolve_path(base_dir, args.output_dir)

    print(f"[MASK-SFT] model={model_path}")
    print(f"[MASK-SFT] data={data_file}")
    print(f"[MASK-SFT] output={output_dir}")
    if args.print_data_stats:
        print_data_stats(data_file)

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_path,
        max_seq_length=args.max_seq_length,
        dtype=None,
        load_in_4bit=args.load_in_4bit,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=args.lora_r,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=args.lora_alpha,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=args.seed,
    )

    dataset = load_dataset("json", data_files=data_file, split="train")

    def formatting_prompts_func(examples):
        texts = []
        for messages in examples["messages"]:
            text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
            texts.append(text)
        return {"text": texts}

    dataset = dataset.map(formatting_prompts_func, batched=True, num_proc=args.dataset_num_proc)

    training_args = SFTConfig(
        output_dir=output_dir,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation,
        warmup_steps=args.warmup_steps,
        num_train_epochs=args.epochs,
        max_steps=args.max_steps,
        learning_rate=args.learning_rate,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_strategy="steps",
        optim="adamw_8bit",
        weight_decay=0.01,
        seed=args.seed,
        report_to=args.report_to,
        dataset_text_field="text",
        max_length=args.max_seq_length,
        dataset_num_proc=args.dataset_num_proc,
        packing=args.packing,
    )

    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset,
        args=training_args,
    )

    trainer.train()
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"[MASK-SFT] saved adapter/tokenizer to {output_dir}")


if __name__ == "__main__":
    main()
